"""
App Boot settings for mysite project.

Generated by 'appboot startproject' using App Boot.
"""
from pathlib import Path

from appboot.conf import DataBases

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR: Path = Path(__file__).resolve().parent.parent

PROJECT_NAME: str = 'mysite'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG: bool = True

ALLOWED_HOSTS: list[str] = ['*']

ROOT_URLCONF: str = 'mysite.urls'

# Database
DATABASES: DataBases = DataBases(
    default=dict(url=f'sqlite+aiosqlite:///{BASE_DIR}/db.sqlite3', echo=DEBUG)
)
